#!/usr/bin/env python

import sys
sys.path.append("/home/vifon/projects/scripts/color-paths")
import string_colorizer
import re
import subprocess
from sys import argv
import hashlib

def main():
    command = subprocess.Popen(["git", "annex", "list"] + argv[1:],
                               stdout = subprocess.PIPE)
    colorizer = string_colorizer.string_colorizer(hashfunc=hashlib.md5,
                                                  colors=["{};1".format(x) for x in [31, 32, 33, 34, 35, 36]])
    colors = []
    for line in command.stdout:
        line = line.decode().rstrip('\n')
        colors.append(colorizer.choose_color(re.search(r'^\|*(.*)', line).group(1)))
        line = re.sub(r'^(\|*)([^|].*)', lambda m: m.group(1) + colors[-1] + m.group(2) + colorizer.reset, line)
        print(line)
        if re.search(r'^\|+$', line):
            break

    for line in command.stdout:
        line = list(line.decode().rstrip('\n'))
        for i in range(0, len(colors)):
            if line[i] == "X":
                line[i] = colors[i] + line[i] + colorizer.reset
        print("".join(line))

if __name__ == "__main__":
    main()
