#!/usr/bin/env python

import sys
sys.path.append("/home/vifon/projects/scripts/color-paths")
import string_colorizer
import re
import subprocess
from sys import argv
import hashlib
from collections import namedtuple

def main():
    command = subprocess.Popen(["git", "annex", "list"] + argv[1:],
                               stdout = subprocess.PIPE)
    colorizer = string_colorizer.string_colorizer(hashfunc=hashlib.md5,
                                                  colors=["{};1".format(x) for x in [31, 32, 33, 34, 35, 36]])
    RemoteInfo = namedtuple("RemoteInfo", ["color", "name"])
    remotes = []
    for line in command.stdout:
        line = line.decode().rstrip('\n')
        match = re.match(r'^(\|*)([^|].*)', line)
        if match:
            remotes.append(RemoteInfo(colorizer.choose_color(match.group(2)),
                                      match.group(2)))
            line = match.group(1) + remotes[-1].color + match.group(2) + colorizer.reset
        print(line)
        if not match:
            break

    for line in command.stdout:
        line = list(line.decode().rstrip('\n'))
        for i in range(0, len(remotes)):
            if line[i] == "X":
                line[i] = remotes[i].color + remotes[i].name[0] + colorizer.reset
        print("".join(line))

if __name__ == "__main__":
    main()
