#!/usr/bin/env python

from __future__ import print_function

import sys
import path_colorizer
import re
import subprocess
from sys import argv

def main():
    command = subprocess.Popen(["git", "annex", "log"] + argv[1:],
                               stdout = subprocess.PIPE)
    colorizer = path_colorizer.path_colorizer()
    def apply_colors(match):
        return (("\033[32m" if match.group(1) == '+' else "\033[31m") +
                match.group(1) +
                " " +
                match.group(2) + colorizer.reset +
                " " +
                colorizer.colorize_path(match.group(3)) +
                " | " +
                colorizer.colors[2] + match.group(4) + colorizer.reset +
                " -- " +
                colorizer.colorize(match.group(5)))
    for line in command.stdout:
        line = line.decode('utf8')
        line = re.sub(r"^([+-]) (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) (.*) \| ([a-f0-9-]+) -- (.*)", apply_colors, line)
        print(line, end="")

if __name__ == "__main__":
    main()
