#!/usr/bin/env python

from __future__ import print_function

import sys
import string_colorizer
import re
import subprocess
from sys import argv

def main():
    command = subprocess.Popen(["git", "annex", "whereis"] + argv[1:],
                               stdout = subprocess.PIPE)
    colorizer = string_colorizer.string_colorizer()
    def color_remotes(match):
        return (colorizer.colors[0] + match.group(1) + colorizer.reset +
                " -- " +
                colorizer.colorize(match.group(2)))
    def color_copies(match):
        return colorizer.colors[8] + match.group(1) + colorizer.reset
    for line in command.stdout:
        line = line.decode()
        line = re.sub(r"([a-f0-9-]+) -- (.*)", color_remotes, line)
        line = re.sub(r"(\(\d+ cop(?:y|ies)\))", color_copies, line)
        print(line, end="")

if __name__ == "__main__":
    main()
